#!/usr/bin/env bash
# Generated by services/ingest/load_catalog.py. Do not edit by hand.
#
# Uploads catalogue source images to R2 under the contracts.md key layout,
# catalog/{merchant}/{productId}/source.jpg. Re-running overwrites, which is safe.
#
# Needs wrangler authenticated: run `npx wrangler login` from workers/ first.
#
# Not `set -e`: one merchant's dead CDN link should not abandon the rest of the
# batch. Failures are counted and reported, and the script exits non-zero if any.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INGEST_DIR="/Users/pauligwe/testclaude/HTN-2026/services/ingest"
BUCKET="full-scale-objects"
WRANGLER_DIR="$INGEST_DIR/../../workers"

if [ ! -d "$WRANGLER_DIR/node_modules" ]; then
  echo "ERROR: workers/node_modules missing. Run npm install in workers/ first." >&2
  exit 1
fi

fail=0
ok=0

put_local() {
  if [ ! -f "$2" ]; then
    echo "MISS  $1 (no file at $2)" >&2; fail=$((fail + 1)); return
  fi
  if ( cd "$WRANGLER_DIR" && npx wrangler r2 object put "$BUCKET/$1" \
        --file "$2" --content-type image/jpeg --remote >/dev/null 2>&1 ); then
    ok=$((ok + 1)); echo "ok    $1"
  else
    fail=$((fail + 1)); echo "FAIL  $1" >&2
  fi
}

put_remote() {
  tmp="$(mktemp)"
  if ! curl -fsSL --max-time 60 "$2" -o "$tmp"; then
    echo "MISS  $1 (fetch failed: $2)" >&2; fail=$((fail + 1)); rm -f "$tmp"; return
  fi
  put_local "$1" "$tmp"
  rm -f "$tmp"
}

put_local "catalog/Floyd_Home/9240389320866/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9240389320866/source.jpg"
put_local "catalog/Floyd_Home/8915805733026/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8915805733026/source.jpg"
put_local "catalog/Floyd_Home/8936217018530/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8936217018530/source.jpg"
put_local "catalog/Poly___Bark/15360102793289/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360102793289/source.jpg"
put_local "catalog/Floyd_Home/9286863519906/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9286863519906/source.jpg"
put_local "catalog/Bend_Goods/534930227235/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/534930227235/source.jpg"
put_local "catalog/Floyd_Home/8732662497442/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8732662497442/source.jpg"
put_local "catalog/Poly___Bark/15693277790281/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15693277790281/source.jpg"
put_local "catalog/Poly___Bark/15360130875465/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360130875465/source.jpg"
put_local "catalog/Floyd_Home/9286983614626/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9286983614626/source.jpg"
put_local "catalog/Bend_Goods/534906896419/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/534906896419/source.jpg"
put_local "catalog/Poly___Bark/15649495351369/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15649495351369/source.jpg"
put_local "catalog/Poly___Bark/15485789306953/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15485789306953/source.jpg"
put_local "catalog/Poly___Bark/15360130842697/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360130842697/source.jpg"
put_local "catalog/Floyd_Home/9305690144930/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9305690144930/source.jpg"
put_local "catalog/Bend_Goods/534972727331/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/534972727331/source.jpg"
put_local "catalog/Poly___Bark/15608340643913/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15608340643913/source.jpg"
put_local "catalog/Poly___Bark/15610666844233/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15610666844233/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9321549365481/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9321549365481/source.jpg"
put_local "catalog/Floyd_Home/9239485317282/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9239485317282/source.jpg"
put_local "catalog/Bend_Goods/9752668668184/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/9752668668184/source.jpg"
put_local "catalog/Poly___Bark/15579187740745/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15579187740745/source.jpg"
put_local "catalog/Poly___Bark/15610829307977/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15610829307977/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9321542779113/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9321542779113/source.jpg"
put_local "catalog/Floyd_Home/8922323910818/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8922323910818/source.jpg"
put_local "catalog/Bend_Goods/8881066705176/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8881066705176/source.jpg"
put_local "catalog/Poly___Bark/15551738773577/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15551738773577/source.jpg"
put_local "catalog/Poly___Bark/15564037685321/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15564037685321/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9321534226665/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9321534226665/source.jpg"
put_local "catalog/Floyd_Home/9244428501154/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9244428501154/source.jpg"
put_local "catalog/Bend_Goods/8549637226776/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8549637226776/source.jpg"
put_local "catalog/Poly___Bark/15547970682953/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15547970682953/source.jpg"
put_local "catalog/Poly___Bark/15561087385673/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15561087385673/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9321386475753/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9321386475753/source.jpg"
put_local "catalog/Floyd_Home/9239597482146/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9239597482146/source.jpg"
put_local "catalog/Bend_Goods/8451502113048/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8451502113048/source.jpg"
put_local "catalog/Poly___Bark/15387576827977/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15387576827977/source.jpg"
put_local "catalog/Poly___Bark/15539724877897/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15539724877897/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9321256124649/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9321256124649/source.jpg"
put_local "catalog/Floyd_Home/9239610327202/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9239610327202/source.jpg"
put_local "catalog/Poly___Bark/15793957371977/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15793957371977/source.jpg"
put_local "catalog/Poly___Bark/15522838741065/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15522838741065/source.jpg"
put_local "catalog/Poly___Bark/15360237273161/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360237273161/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9316244422889/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9316244422889/source.jpg"
put_local "catalog/Floyd_Home/9246282842274/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9246282842274/source.jpg"
put_local "catalog/Poly___Bark/15797869215817/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15797869215817/source.jpg"
put_local "catalog/Poly___Bark/15329534640201/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15329534640201/source.jpg"
put_local "catalog/Poly___Bark/15360099582025/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360099582025/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9305280381161/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9305280381161/source.jpg"
put_local "catalog/Floyd_Home/9077008498850/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/9077008498850/source.jpg"
put_local "catalog/Poly___Bark/15797666709577/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15797666709577/source.jpg"
put_local "catalog/Poly___Bark/15329534672969/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15329534672969/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9298981945577/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9298981945577/source.jpg"
put_local "catalog/Floyd_Home/8836821057698/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8836821057698/source.jpg"
put_local "catalog/Poly___Bark/15797391851593/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15797391851593/source.jpg"
put_local "catalog/Poly___Bark/15360096337993/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360096337993/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9420686229737/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9420686229737/source.jpg"
put_local "catalog/Floyd_Home/8830910103714/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8830910103714/source.jpg"
put_local "catalog/Poly___Bark/15796244021321/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15796244021321/source.jpg"
put_local "catalog/Poly___Bark/15360096272457/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360096272457/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9299128877289/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9299128877289/source.jpg"
put_local "catalog/Floyd_Home/8751821521058/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8751821521058/source.jpg"
put_local "catalog/Poly___Bark/15796021329993/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15796021329993/source.jpg"
put_local "catalog/Poly___Bark/15360097910857/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360097910857/source.jpg"
put_local "catalog/Kohara___Co__CA_lighting/9299127927017/source.jpg" "$INGEST_DIR/prebake/catalog/Kohara___Co__CA_lighting/9299127927017/source.jpg"
put_local "catalog/Floyd_Home/8608650657954/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8608650657954/source.jpg"
put_local "catalog/Poly___Bark/15795933904969/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15795933904969/source.jpg"
put_local "catalog/Poly___Bark/15360097878089/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15360097878089/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15353340985389/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15353340985389/source.jpg"
put_local "catalog/Floyd_Home/8608648855714/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8608648855714/source.jpg"
put_local "catalog/Poly___Bark/15795399000137/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15795399000137/source.jpg"
put_local "catalog/InStyle_Home__CA/8955099480286/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/8955099480286/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15353341050925/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15353341050925/source.jpg"
put_local "catalog/Floyd_Home/8691260522658/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8691260522658/source.jpg"
put_local "catalog/Poly___Bark/15794247106633/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15794247106633/source.jpg"
put_local "catalog/InStyle_Home__CA/8955099742430/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/8955099742430/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373989314605/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373989314605/source.jpg"
put_local "catalog/Floyd_Home/8691303252130/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8691303252130/source.jpg"
put_local "catalog/Poly___Bark/15793229201481/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15793229201481/source.jpg"
put_local "catalog/InStyle_Home__CA/8955099807966/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/8955099807966/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373989347373/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373989347373/source.jpg"
put_local "catalog/Floyd_Home/8691227394210/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8691227394210/source.jpg"
put_local "catalog/Poly___Bark/15792973185097/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15792973185097/source.jpg"
put_local "catalog/InStyle_Home__CA/8960728826078/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/8960728826078/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373989380141/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373989380141/source.jpg"
put_local "catalog/Floyd_Home/8691192299682/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8691192299682/source.jpg"
put_local "catalog/Poly___Bark/15791501246537/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15791501246537/source.jpg"
put_local "catalog/InStyle_Home__CA/8695995990238/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/8695995990238/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373989412909/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373989412909/source.jpg"
put_local "catalog/Floyd_Home/8691171557538/source.jpg" "$INGEST_DIR/prebake/catalog/Floyd_Home/8691171557538/source.jpg"
put_local "catalog/Poly___Bark/15791407988809/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15791407988809/source.jpg"
put_local "catalog/InStyle_Home__CA/9013924069598/source.jpg" "$INGEST_DIR/prebake/catalog/InStyle_Home__CA/9013924069598/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373989445677/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373989445677/source.jpg"
put_local "catalog/Bend_Goods/8640584778008/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8640584778008/source.jpg"
put_local "catalog/Poly___Bark/15791127429193/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15791127429193/source.jpg"
put_local "catalog/Bend_Goods/8668094300440/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8668094300440/source.jpg"
put_local "catalog/2Modern__lighting___furniture/15373990166573/source.jpg" "$INGEST_DIR/prebake/catalog/2Modern__lighting___furniture/15373990166573/source.jpg"
put_local "catalog/Bend_Goods/8640583926040/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/8640583926040/source.jpg"
put_local "catalog/Poly___Bark/15791039479881/source.jpg" "$INGEST_DIR/prebake/catalog/Poly___Bark/15791039479881/source.jpg"
put_local "catalog/Bend_Goods/534931406883/source.jpg" "$INGEST_DIR/prebake/catalog/Bend_Goods/534931406883/source.jpg"

echo
echo "uploaded $ok, failed $fail"
if [ "$fail" -gt 0 ]; then
  echo "Re-run this script to retry the failures; overwriting is safe." >&2
  exit 1
fi
