#!/usr/bin/env bash
# Generate workers/.wrangler.offline.toml from wrangler.toml, with the remote-only bindings
# removed, then print the command to run it.
#
# Why this exists. Vectorize, Workers AI and Browser Run have no local simulation. `remote =
# true` makes `wrangler dev` proxy them to the real service, which needs `wrangler login` and
# an internet connection. With neither, `wrangler dev` refuses to start at all — not just for
# those three routes, but for everything.
#
# That is the wrong failure at a hackathon venue. The demo spine — scan, upload, store, version,
# push, SSE to the headset — uses only D1, R2, KV, Queues, Durable Objects and Workflows, and
# every one of those simulates locally. This config lets the spine run with no account and no
# network.
#
# It is GENERATED, never edited, so it cannot drift from wrangler.toml.
#
#   bash offline-config.sh && cd ../../workers && npx wrangler dev -c .wrangler.offline.toml
#
# What does not work in this mode, and fails loudly rather than quietly:
#   /v1/search        -> falls back to the d1-fallback ranker (X-Ranker header says so)
#   /v1/scout         -> no AI binding, so the scout agent cannot run
#   POST /v1/solve    -> no AI binding, so the layout agent cannot plan
#   read_listing      -> no Browser Run binding

set -euo pipefail
cd "$(dirname "$0")/../../workers"

python3 - <<'PY'
import pathlib, re

src = pathlib.Path("wrangler.toml").read_text()

# Drop the three blocks whose services only exist remotely. A TOML block runs from its header
# to the next blank line followed by another header or a comment block, so split on headers.
out, skipping = [], False
for line in src.splitlines(keepends=True):
    header = re.match(r"^\[+([a-z_.]+)\]+", line)
    if header:
        skipping = header.group(1) in {"vectorize", "ai", "browser"}
    if not skipping:
        out.append(line)

text = "".join(out)
banner = (
    "# GENERATED by infra/cloudflare/offline-config.sh. Do not edit; edit wrangler.toml.\n"
    "# Vectorize, Workers AI and Browser Run are removed because they have no local\n"
    "# simulation and would force an authenticated remote session.\n\n"
)
pathlib.Path(".wrangler.offline.toml").write_text(banner + text)
print("wrote workers/.wrangler.offline.toml")
PY

echo
echo "Run it with:"
echo "  cd workers && npx wrangler dev -c .wrangler.offline.toml"
